config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from semillas_backend.users.views import FacebookLogin

import allauth.account.views as allauth_views

urlpatterns = [

    # API
    url(r'^api/v1/user/', include('semillas_backend.users.api_urls', namespace='api_users')),
    url(r'^api/v1/service/', include('services.urls', namespace='api_service')),
    url(r'^api/v1/wallet/', include('wallet.urls', namespace='api_wallet')),


    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^$', TemplateView.as_view(template_name='landing/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('semillas_backend.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^rest-auth/facebook/$', FacebookLogin.as_view(), name='fb_login'),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/account-confirm-email/(?P<key>[-:\w]+)/$', allauth_views.confirm_email,
        name="account_confirm_email"),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^', include('django.contrib.auth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^landing/', include('landing.urls', namespace='landing')),
    url(r'^docs/', include('rest_framework_docs.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    import debug_toolbar
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

landing/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

from django.views.generic import TemplateView

# place app url patterns here


urlpatterns = [
    # url pattern for the userlistview

    url(
        regex=r'^porque/$',
        view=TemplateView.as_view(template_name='landing/porque.html'),
        name='porque'
    ),
    url(
        regex=r'^how_it_works/$',
        view=TemplateView.as_view(template_name='landing/how_it_works.html'),
        name='how_it_works'
    ),
    url(
        regex=r'^people/$',
        view=TemplateView.as_view(template_name='landing/who_we_are.html'),
        name='people'
    ),
    url(
        regex=r'^privacy/$',
        view=TemplateView.as_view(template_name='landing/privacy.html'),
        name='privacy'
    ),
]

landing/models.py
from django.db import models

# Create your models here.

landing/forms.py
from django import forms

# place form definition here

landing/views.py
# Create your views here.

landing/templates/landing/contact.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load i18n %}
        <h2>
         <text><i class="fa fa-pencil fa-3" aria-hidden="true"></i>
             {% trans "Contacto" %}
         </text>
        </h2>
        <hr>
        <div class="content">
         <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-12" >
         <p>
            {% trans "Puedes contactarnos en" %}
            <u><a class="mailto" href="mailto:info.semillasocial@gmail.com"> info.semillasocial@gmail.com</a></u>
         </p>
         <p>
         {% trans "También puedes conocernos en " %} <a href="{% url 'landing:people' %}">{% trans "este link" %}</a>.
         </p>
          </div>
         </div>
<br><br><br><br><br>
{% endblock %}

landing/templates/landing/development.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load i18n %}
    <h2>
         <text>
            <i class="fa fa-code-fork" aria-hidden="true"></i>
             {% trans "Version 0.1" %}
         </text>
    </h2>
    <hr>
    <div class="container">
        <div class="row">
                <p>The stack is Python/Django + Django Rest Framework Running on Heroku. </p>
                <p>You can sign-up in this page and then visit: https://www.semillasocial.org/docs to browse our API REST</p>
                <p>The Web client is being crafted with ReactJS + Redux.</p>
                <p>Start your own Mobile Client!!</p>
                <p>Here is the <a href="https://github.com/Semillas">Github Account</a></p>
            </div><!--end of cols group CERO-->
            <div class="cols-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <h2><text>
                <i class="fa fa-archive" aria-hidden="true"></i>
                    Software:
                </text></h2>
                <hr>
            </div>
             <div class="cols-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                 <div class="card text-xs-center">
                     <div class="card-block">
                        <h4 class="card-title">Django</h4>
                        <img src="{% static 'landing/images/django.png' %}" class="center-block img-fluid" alt="Django image">
                        <p class="card-text">The awesome framework that makes this possible.</p>
                        <a href="http://www.djangoproject.com" class="btn btn-link">Website</a>
                     </div>
                 </div>
                 <div class="card text-xs-center">
                     <div class="card-block">
                        <h4 class="card-title">Docker</h4>
                         <img src="{% static 'landing/images/docker.png' %}" class="center-block img-fluid" alt="Docker image">
                        <p class="card-text">Docker is what holds everything and makes it easy to export.</p>
                        <a href="https://www.docker.com/" class="btn btn-link">Website</a>
                     </div>
                 </div>
                 <div class="card text-xs-center">
                     <div class="card-block">
                        <h4 class="card-title">GitHub</h4>
                         <img src="{% static 'landing/images/gitHub.png' %}" class="center-block img-fluid" alt="GitHub image">
                        <p class="card-text">The repository used to control software version.</p>
                        <a href="https://www.github.com" class="btn btn-link">Website</a>
                        <a href="https://github.com/Semillas" class="btn btn-link">Our repository</a>
                     </div>
                 </div>
                 <div class="card text-xs-center">
                     <div class="card-block">
                        <h4 class="card-title">Gunicorn</h4>
                         <img src="{% static 'landing/images/gunicorn.jpg' %}" class="center-block img-fluid" alt="Gunicorn Image">
                        <p class="card-text">Things get served with Gunicorn.</p>
                        <a href="http://gunicorn.org" class="btn btn-link">Website</a>
                     </div>
                 </div>
                 <div class="card text-xs-center">
                     <div class="card-block">
                        <h4 class="card-title">Slack</h4>
                        <img src="{% static 'landing/images/web-slack.png' %}" class="center-block img-fluid" alt="Slack Image">
                        <p class="card-text">The future of chats. Is where the team gets updated and have fun.</p>
                        <a href="https://slack.com/" class="btn btn-link">Website</a>
                        <a href="https://semillas.slack.com/" class="btn btn-link">Our channel</a>
                     </div>
                 </div>
                 <div class="card text-xs-center">
                     <div class="card-block">
                        <h4 class="card-title">HTML5</h4>
                        <img src="{% static 'landing/images/html5.png' %}" class="center-block img-fluid" alt="HTML5 Image">
                        <p class="card-text">The main Internet front language.</p>
                        <a href="https://www.w3.org/TR/html5/" class="btn btn-link">Website</a>
                     </div>
                 </div>
                 <div class="card text-xs-center">
                     <div class="card-block">
                        <h4 class="card-title">Heroku</h4>
                         <img src="{% static 'landing/images/heroku.png' %}" class="center-block img-fluid" alt="Heroku Image">
                        <p class="card-text">Is the place where our code runs.</p>
                        <a href="https://www.heroku.com/" class="btn btn-link">Website</a>
                     </div>
                 </div>
             </div><!--end of cols group TWO-->

             <div class="cols-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                 <div class="card text-xs-center">
                     <div class="card-block">
                        <h4 class="card-title">Python</h4>
                        <img src="{% static 'landing/images/python.png' %}" class="center-block img-fluid" alt="Python Image">
                        <p class="card-text">It's the powerful languaje where all is made with, such as Django.</p>
                        <a href="https://www.python.org" class="btn btn-link">Website</a>
                     </div>
                 </div>
                 <div class="card text-xs-center">
                     <div class="card-block">
                        <h4 class="card-title">Linux</h4>
                         <img src="{% static 'landing/images/tux.png' %}" class="center-block img-fluid" alt="Tux Image">
                        <p class="card-text">We love GNU-Linux and the whole project is under it. We are Linux enthusiasts!</p>
                        <a href="https://www.linux.com/" class="btn btn-link">Website</a>
                     </div>
                 </div>
                <div class="card text-xs-center">
                     <div class="card-block">
                        <h4 class="card-title">Swagger</h4>
                         <img src="{% static 'landing/images/swagger.png' %}" class="center-block img-fluid" alt="Swagger Image">
                        <p class="card-text">This swagg software helps us test quality code.</p>
                        <a href="http://swagger.io" class="btn btn-link">Website</a>
                     </div>
                 </div>
                 <div class="card text-xs-center">
                     <div class="card-block">
                        <h4 class="card-title">Sentry</h4>
                         <img src="{% static 'landing/images/sentry.png' %}" class="center-block img-fluid" alt="Sentry Image">
                        <p class="card-text">For fixing and log errors on the server.</p>
                        <a href="https://sentry.io" class="btn btn-link">Website</a>
                     </div>
                 </div>
                 <div class="card text-xs-center">
                     <div class="card-block">
                        <h4 class="card-title">JavaScript</h4>
                         <img src="{% static 'landing/images/JS.png' %}" class="center-block img-fluid" alt="JavaScript Image">
                        <p class="card-text">We use JavaScript to make the web more friendable :).</p>
                        <a href="#" class="btn btn-link">Website</a>
                     </div>
                 </div>
                <div class="card text-xs-center">
                     <div class="card-block">
                        <h4 class="card-title">Bootstrap</h4>
                         <img src="{% static 'landing/images/bootstrap.png' %}" class="center-block img-fluid" alt="Bootstrap Image">
                        <p class="card-text">The frontend framework used to make this gorgeous!</p>
                        <a href="https://www.getbootstrap.com" class="btn btn-link">Website</a>
                     </div>
                 </div>
                 <div class="card text-xs-center">
                     <div class="card-block">
                        <h4 class="card-title">License</h4>
                         <img src="{% static 'landing/images/creativeCommons.png' %}" class="center-block img-fluid" alt="License Image">
                        <p class="card-text">Our code is free and open.</p>
                        <a href="http://creativecommons.org" class="btn btn-link">Website</a>
                     </div>
                 </div>
              </div><!--end of cols group TRHEE-->
             </div>
        </div>
    </div>
{% endblock %}

landing/templates/landing/home.html
{% extends "base.html" %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load staticfiles %}

{% block header-text %}
  <div class="page-head--content">
    <p class="header-text">{% trans "App móvil de compraventa de bienes y servicios con monedas virtuales." %}</p>
  </div>
{% endblock header-text %}

{% block content %}

  <div class="container-fluid">
    <div class="row" style="align-items: center; display: flex; flex-wrap: wrap;">
      <div class="product_image col-sm-5 text-center">

        <img src="{% static 'landing/images/product/feed.png' %}" alt="web phone feed" style="width: 85%;">
      </div>
      <div class="description col-sm-7">
        <p class="product-title" style="font-size:26px;"><strong>{% trans "Marketplace Social " %}</strong></p>
        <p class="product-description" style="font-size:20px; color:grey;">{% trans "Se basa en la abundancia de recursos, la capacidad creativa, artística, manual e intelectual de todos sus miembros." %}</p>
        <p class="product-description" style="font-size:20px; color:grey;">{% trans "Los bienes y servicios ofertados aparecen ordenados por proximidad" %}</p>
      </div>
    </div>
  </div>

  <div class="container-fluid section-two" style="position: relative; z-index: 1;">
    <div class="bg" style="background: url('{% static 'landing/images/product_background.jpg' %}') no-repeat center center fixed; background-size:100% auto;position: absolute;
    z-index: -1;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    /*background: url(test.jpg) center center;*/
    opacity: 0.15;
    width: 100%;
    height: 100%;"></div>
    <div class="row" style="align-items: center; display: flex; flex-wrap: wrap-reverse;">
      <div class="description col-sm-7 text-right" style="vertical-align: middle;">
        <p class="product-title" style="font-size:26px;"><strong>{% trans "Democrática" %}</strong></p>
        <p style="font-size:20px; color:grey;">{% trans "Las decisiones se toman por votación entre los miembros" %}</p>
        <a href="/landing/people/" class="btn btn-primary btn-round-lg" style="border-radius: 40.5px; width: 210px; max-width: 300px;border-color:#67b26f;color:#67b26f;background-color:transparent;font-size: 20px; text-transform:none;"><strong>{% trans "Ven y Participa" %}</strong></a>
      </div>
      <div class="product_image col-sm-5 text-center">
        <img src="{% static 'landing/images/product/user_profile.png' %}" alt="user profile" style="width:85%;">
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row" style="align-items: center; display: flex; flex-wrap: wrap;">
      <div class="product_image col-sm-5 text-center">
        <img  src="{% static 'landing/images/product/offer_detail.png' %}" alt="user profile" style="width:85%;">
      </div>

      <div class="description col-sm-7">
        <p class="product-title" style="font-size:26px;">{% trans "Moneda Social " %}</p>
        <p style="font-size:20px; color:grey;">{% trans "Semillas promociona el bien común. Retribuyendo en semillas trabajos a la comunidad o acciones cívicas." %}</p>
      </div>
    </div>
  </div>


{% endblock content %}

landing/templates/landing/how_it_works.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load i18n %}


	<div class="container">

		<h4 class="c-heading-sub" style="font-size:32px;">{% trans "Cómo Funciona" %}</h4>
    <p style="font-size:19px;">{% trans "Tú empiezas con una cuenta de 0 semillas, pero ofreciendo algo (un servicio o un producto). Cuando alguien lo quiere, te paga con semillas, de forma que tú sumas semillas en tu cuenta y ella se las resta de la suya. Por ejemplo, tú ofreces naranjas a 3 semillas el kg. A Julia, que le encantan las naranjas, le interesa la oferta, y quiere 1 kg. Tú le das las naranjas y te sumas 3 semillas. Julia se restará 3 semillas. Y esta es la forma de conseguir semillas!!"%}</p>

	</div>
	<div class="container">
    <h3 class="c-heading-sub" style="color:#4ca2cd;font-size:27px;">{% trans "Entonces, ¿puedo tener negativa la cuenta de semillas?" %}</h3>
    <p style="font-size:19px;">
      {% blocktrans with limit=-20 %}
      Claro que puedes. Hay un límite, actualmente es {{ limit }}, del que ya no podrás pasar. Así que tendrás que ofrecer algo que interese a la gente para poder equilibrar tu cuenta. No te preocupes, seguro que surge algo que tú puedes hacer por ell@s, y poder sumar semillas. La semilla está pensada para que las usuarias vayamos pasando constantemente de saldos negativos a positivos y viceversa. Un saldo positivo indica que hemos aportado a la red más de lo que hemos consumido, mientras que un saldo negativo indica que hemos consumido de la red más de lo que hemos aportado.
      {% endblocktrans %}
    </p>
	</div>

	<div class="container">
    <h3 class="c-heading-sub" style="color:#4ca2cd;font-size:27px;">{% trans "Redistribución Mensual" %}</h3>
    <p style="font-size:19px;">
      {% blocktrans %}
      Mensualmente se aplicará una redistribución de la Semilla del 5%. A quienes tengan saldo positivo, se les restará un 5% de la cantidad, mientras que si tu saldo es negativo, se te sumará un 5% de la cantidad negativa que tengas. Con el paso del tiempo todas las cuentas convergen a 0.
      {% endblocktrans %}
    </p>
	</div>


	<div class="container">
    <h3 class="c-heading-sub" style="color:#4ca2cd;font-size:27px;">{% trans "Valores de Referencia" %}</h3>
    <p style="font-size:19px;">
      {% blocktrans %}
      La referencia decidida para los servicios es de 10 Semillas/hora, siempre de manera orientativa. No es que vaya a haber nadie controlando ni que esto no pueda variar algo en cada caso. No obstante, aplicando todas el mismo índice podemos asegurar que el sistema funciona de manera equitativa.
      {% endblocktrans %}
    </p>
	</div>


	<div class="container">
    <h3 class="c-heading-sub" style="color:#4ca2cd;font-size:27px;">{% trans "Precios en Semillas y en Euros" %}</h3>
    <p style="font-size:19px;">
      {% blocktrans %}
        Pueden existir artículos donde puede ser preciso pagar un porcentaje en Semillas y un porcentaje en Euros. Esto es debido a que el prosumidor tiene unos gastos fijos en Euros para poder ofrecer dichos bienes y servicios.
      {% endblocktrans %}
    </p>
	</div>

	<div class="container">
    <h3 class="c-heading-sub" style="color:#4ca2cd;font-size:27px;">{% trans "Únete a nosotros y ayúdanos a decidir" %}</h3>
    <p style="font-size:19px;">
      {% blocktrans %}
      Somos un equipo deslocalizado. Queremos ser más abiertos y asamblearios, estamos en proceso. Únete a nosotros en este camino. Escribe a info.semillasocial@gmail.com.
      {% endblocktrans %}
    </p>
	</div>
{% endblock %}

landing/templates/landing/porque.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load i18n %}

	<div class="container">
		<h4 class="c-heading-sub" style="font-size:32px;">{% trans "Misión" %}</h4>
	    <p style="font-size:19px;">{% trans " Semillas es una tecnología abierta y transparente al servicio de lo humano. Es una herramienta de cambio social por su potencia para construir redes entre iguales por donde circula, se distribuye y se intercambia la abundancia de recursos, la capacidad creativa, artística, manual e intelectual de todos sus miembros." %}</p>
		<div class="container-fluid">
			<div class="row" style="display: flex; flex-wrap:wrap;">

			    <div class="col-sm-7" >
				    <p style="font-size:19px;">{% trans " La Semilla otorga soberanía local,  está sujeta a los procesos participativos y democráticos de las personas que usan la moneda y sus relaciones locales." %}</p>


				    <h3 class="c-heading-sub" style="color:#4ca2cd;font-size:27px;">{% trans "Social" %}</h3>
			        <p style="font-size:19px;">

                {% blocktrans %}
                Porque las personas que la hemos creado queremos visibilizar la economía de cuidados y empoderar a cada individuo en sus habilidades. A través de las categorías para crear servicios en la app queremos inferir un uso social, solidario, sostenible y ecológico.
                {% endblocktrans %}
              </p>
			        <p style="font-size:19px;">

                {% blocktrans %}
                También queremos permitir la creación de moneda para pagar acciones sociales que beneficien al común. Buscamos organos o asociaciones que quieran realizar trabajos para el beneficio de todos y retribuirlo en Semillas (como por ejemplo arreglar su centro social).
                {% endblocktrans %}
                <a href=#bank> {% trans "Ir al Banco de Semillas" %} </a>
              </p>

				    <h3 class="c-heading-sub" style="color:#4ca2cd;font-size:27px;">{% trans "Software Libre" %}</h3>
			        <p style="font-size:19px;">{% trans " Todo el código que escribimos lo publicamos instantáneamente en Internet:"%}<a href="https://github.com/semillas"> https://github.com/semillas</a></p>
			        <p style="font-size:19px;">{% trans  " Si alguien modifica el producto, está obligado también a publicarlo en internet, pudiendo el resto de desarrolladores adoptar las mejoras." %}</p>
			        <p style="font-size:19px;">{% trans  " Por tanto es 100% redistribuible, copiable y modificable." %}</p>
			        <p style="font-size:19px;">{% trans  " No se pagan licencias por su uso." %}</p>
			        <p style="font-size:19px;">{% trans  " Cualquier entidad podría crearse su propia moneda utilizando este software." %}</p>

			    </div>
			    <div class="col-sm-5">
			    	<img class="img-responsive" src="{% static 'landing/images/product/feed2.png' %}" alt="">
			    </div>
			</div>
		</div>
	    <h3 class="c-heading-sub" style="color:#4ca2cd;font-size:27px;">{% trans "Crédito Mutuo" %}</h3>
    	<p style="font-size:19px;">{% trans " Semillas es un sistema de crédito mutuo. La suma de las cantidades positivas y negativas de todos sus miembros es 0. Propone una oxidación equitativa para incentivar el uso y evitar la acumulación." %}</p>
    	<p style="font-size:19px;">{% trans " Las Semillas cobran existencia en el mismo momento en el que dos personas o colectivos aceptan libremente un intercambio: a una se le suma el valor convenido en semillas y a otra se le resta esa misma cantidad." %}</p>
    	<p style="font-size:19px;">{% trans " Un saldo positivo indica que hemos aportado a la red más de lo que hemos consumido, mientras que un saldo negativo indica que hemos consumido de la red más de lo que hemos aportado. Así, cuando nuestro saldo sea negativo ofreceremos algún producto o servicio para ponernos en positivo, y cuando estemos en positivo consumiremos y reduciremos hasta valores negativos. "%}</p>

		<div class="container-fluid">
			<div class="row" style="display: flex; flex-wrap: wrap;">
			    <div class="col-sm-7" >
			        <h3 class="c-heading-sub" style="color:#4ca2cd;font-size:27px;">{% trans "Plug & Play" %}</h3>
			    	<p style="font-size:19px;">{% trans " A pesar de que hay diferentes grupos y experimentos con iniciativas similares, es muy complicado empezar a formar parte de ellas. Hay que enviar correos, ir a colectivos el día de asamblea. En Semillas darse de alta va a ser cuestión de segundos. "%}</p>

			     	<h3 class="c-heading-sub" style="color:#4ca2cd;font-size:27px;">{% trans "Local & Global" %}</h3>
			    	<p style="font-size:19px;">{% trans " El orden de las ofertas será por proximidad. La proximidad hará que se favorezca al mercado local. Sin embargo, queremos dar una posibilidad tecnológica para poder obtener, a cambio de tus semillas, clases de inglés al otro lado del océano. "%}</p>
			    </div>
			    <div class="col-sm-5">
			    	<img class="img-responsive" src="{% static 'landing/images/product/wallet.png' %}" alt="">
			    </div>
		    </div>
		</div>

	    <h3 class="c-heading-sub" style="color:#4ca2cd;font-size:27px;">{% trans "Moneda Colaborativa" %}</h3>
	    <p style="font-size:19px;">{% trans " Nuestra propuesta no es solo una moneda alternativa, si no también una herramienta para crear redes colaborativas. Propone sinergias con plataformas de economía colaborativa que acepten pago en semillas."%}</p>

	</div>
	<div class="container">
    	<h4 class="c-heading-sub" style="font-size:32px;">{% trans "Catalizador de Sobreranía" %}</h4>
    	<p style="font-size:19px;">{% trans " Semillas Social promociona el bien común. Retribuyendo en semillas trabajos a la comunidad o acciones cívicas.Para ello se apoya en los “Bancos de Semillas” "%}</p>

      <a name="bank"></a>
    	<h3  class="c-heading-sub" style="color:#4ca2cd;font-size:27px;">{% trans "Banco de semillas" %}</h3>
        <p style="font-size:19px;">{% trans " Es un grupo vecinal al cobijo de una institución pública o privada." %}</p>
        <p style="font-size:19px;">{% trans " El Banco de Semillas se encarga de crear y retribuir trabajos a la comunidad (índole social, ecológica, educativa, medioambiental) así como acciones cívicas." %}</p>
        <p style="font-size:19px;">{% trans " El siguiente ejemplo muestra ayuntamiento coordinando un banco de semillas. El ayuntamiento cierra el ciclo monetario aceptando La Semilla en el alquiler de polideportivos, pago de multas, etc. "%}</p>
        <img src="{% static 'landing/images/BancoSemillas.png' %}" style="width: 100%"">
	</div>

{% endblock %}